server:
  port: 1002
spring:
  application:
    name: service-news
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${sc_db_host}:3306/at-dev?characterEncoding=UTF-8
    username: ${sc_db_user}
    password: ${sc_db_pwd}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
