server:
  port: 2001
spring:
  application:
    name: view-web
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: zx5435.com

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: log/a.log
  pattern: # org.springframework.boot.logging.logback.DefaultLogbackConfiguration
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#    console: '%d{yyyy/MM/dd-HH:mm:ss} %level [%thread] %caller{1} - %msg%n'
#  level:
#    root: debug
