server:
  port: 2001
spring:
  application:
    name: view-web
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: zx5435.com

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  hystrix:
    enabled: true

logging:
  file: /Users/zhaoyujie/Desktop/log/a.log
#  pattern:
#    console: '%d{MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M\(%line\) - %msg%n'
#  level:
#    root: debug
