server:
  port: 2001
spring:
  application:
    name: view-web
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: zx5435.com

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  path: log
#  pattern: # org.springframework.boot.logging.logback.DefaultLogbackConfiguration.CONSOLE_LOG_PATTERN
