server:
  port: 2001
spring:
  application:
    name: view-web
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: ${sc_db_host}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  hystrix:
    enabled: true

#logging:
#  level:
#    root: debug
